name: Test
on: push
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Get code  ###This is the first step in the deployment process
        uses: actions/checkout@v2  ## This action checks out the code from the repository
      - name: Install dependencies
        run: npm ci
      ##- name: Lint  ##This is used to  
      ##  run: npm run lint ##This step checks the code for errors and style issues
      - name: Test code ##This step runs the tests to ensure the code works as expected
        run: npm run test  ## This command executes the test suite
      - name: Build code  ## This step compiles the code into a production-ready format
        run: npm run build ## This command builds the application
      - name: Deploy code ## This step deploys the application to the production environment
        run: echo "Deploying..."